################################
# 🦎 KOMODO COMPOSE - MONGO 🦎 #
################################
services:
  mongo:
    image: mongo@sha256:5483a68b6fe7737367be84fb963f0e440e67a87f2e57ea087e608da034e91318
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
    networks:
      - thinknetwork

  core:
    image: ghcr.io/moghtech/komodo-core@sha256:a1cceb4f971443b1e9f2a767788f663d0afb6244ee2135f7fe3fd1036af37ade
    init: true
    labels:
      komodo.skip:
      traefik.enable: "true"
      traefik.docker.network: "thinknetwork"
      traefik.http.routers.komodo.rule: "Host(`komodo.thinkcenter.dev`)"
      traefik.http.routers.komodo.tls: "true"
      traefik.http.services.komodo.loadbalancer.server.port: "9120"
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 9120:9120
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
      KOMODO_HOST: ${KOMODO_HOST}
      KOMODO_TITLE: ${KOMODO_TITLE}
      KOMODO_FIRST_SERVER: ${KOMODO_FIRST_SERVER}
      KOMODO_FIRST_SERVER_NAME: ${KOMODO_FIRST_SERVER_NAME}
      KOMODO_MONITORING_INTERVAL: ${KOMODO_MONITORING_INTERVAL}
      KOMODO_RESOURCE_POLL_INTERVAL: ${KOMODO_RESOURCE_POLL_INTERVAL}
      KOMODO_WEBHOOK_SECRET: ${KOMODO_WEBHOOK_SECRET}
      KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET}
      KOMODO_JWT_TTL: ${KOMODO_JWT_TTL}
      KOMODO_LOCAL_AUTH: ${KOMODO_LOCAL_AUTH}
      KOMODO_INIT_ADMIN_USERNAME: ${KOMODO_INIT_ADMIN_USERNAME}
      KOMODO_INIT_ADMIN_PASSWORD: ${KOMODO_INIT_ADMIN_PASSWORD}
      KOMODO_DISABLE_USER_REGISTRATION: ${KOMODO_DISABLE_USER_REGISTRATION}
      KOMODO_ENABLE_NEW_USERS: ${KOMODO_ENABLE_NEW_USERS}
      KOMODO_DISABLE_NON_ADMIN_CREATE: ${KOMODO_DISABLE_NON_ADMIN_CREATE}
      KOMODO_LOGGING_PRETTY: ${KOMODO_LOGGING_PRETTY}
      KOMODO_PRETTY_STARTUP_CONFIG: ${KOMODO_PRETTY_STARTUP_CONFIG}
      KOMODO_LOGGING_OTLP_ENDPOINT: ${KOMODO_LOGGING_OTLP_ENDPOINT}
      KOMODO_LOGGING_OPENTELEMETRY_SERVICE_NAME: ${KOMODO_LOGGING_OPENTELEMETRY_SERVICE_NAME}
      TZ: ${TZ}
    volumes:
      - keys:/config/keys
      - ${COMPOSE_KOMODO_BACKUPS_PATH}:/backups
    networks:
      - thinknetwork

  periphery:
    image: ghcr.io/moghtech/komodo-periphery@sha256:bd79cf960ed054fe8e02384322303e462448679b1149dde48bbef151417255b1
    init: true
    labels:
      komodo.skip:
    restart: unless-stopped
    environment:
      PERIPHERY_DISABLE_TERMINALS: ${PERIPHERY_DISABLE_TERMINALS}
      PERIPHERY_SSL_ENABLED: ${PERIPHERY_SSL_ENABLED}
      PERIPHERY_INCLUDE_DISK_MOUNTS: ${PERIPHERY_INCLUDE_DISK_MOUNTS}
      PERIPHERY_LOGGING_PRETTY: ${PERIPHERY_LOGGING_PRETTY}
      PERIPHERY_PRETTY_STARTUP_CONFIG: ${PERIPHERY_PRETTY_STARTUP_CONFIG}
      PERIPHERY_LOGGING_OTLP_ENDPOINT: ${PERIPHERY_LOGGING_OTLP_ENDPOINT}
      PERIPHERY_LOGGING_OPENTELEMETRY_SERVICE_NAME: ${PERIPHERY_LOGGING_OPENTELEMETRY_SERVICE_NAME}
      TZ: ${TZ}
      PERIPHERY_CORE_ADDRESS: ${PERIPHERY_CORE_ADDRESS}
      PERIPHERY_CONNECT_AS: ${PERIPHERY_CONNECT_AS}
      PERIPHERY_ONBOARDING_KEY: ${PERIPHERY_ONBOARDING_KEY}
    volumes:
      - keys:/config/keys
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    networks:
      - thinknetwork

volumes:
  mongo-data:
  mongo-config:
  keys:

networks:
  thinknetwork:
    name: thinknetwork
    external: true
