services:
  opencode-server:
    image: ghcr.io/anomalyco/opencode@sha256:db8e378ab557b6891e8532554229f6f110e03fb385ad598526abe575be94276e
    restart: no
    ports:
      - "4096:4096"
    command: "web --port 4096 --mdns --mdns-domain opencode.thinkcenter.dev --cors https://opencode.thinkcenter.dev"
    labels:
      - traefik.enable=true
      - traefik.docker.network=thinknetwork
      - traefik.http.routers.opencode.rule=Host(`opencode.thinkcenter.dev`)
      - traefik.http.routers.opencode.entrypoints=websecure
      - traefik.http.routers.opencode.tls=true
      - traefik.http.services.opencode.loadbalancer.server.port=4096
    env_file:
      - path: .server.env
        required: true
      - path: .secrets.env
        required: true
    volumes:
      - type: bind
        source: ./opencode.jsonc
        target: ${OPENCODE_CONFIG}
      - type: bind
        source: /opt/ai-tooling
        target: ${OPENCODE_CONFIG_DIR}
        read_only: true
      - type: bind
        source: /opt/ai-support
        target: /workspace/ai-support
        read_only: true
    networks:
      - thinknetwork
networks:
  thinknetwork:
    name: thinknetwork
    external: true
