---
platform: linux

image_resource:
  type: registry-image
  source: 
    repository: concourse/oci-build-task
    tag: 0.9

inputs:
  - name: app-source

outputs:
  - name: image

params: 
  CONTEXT: app-source/((build_docker_task_dockerfile_dir_path))
  BUILD_ARG_BACKEND_APP_VERSION: app-source/.git/HEAD

run:
  path: build
