---
platform: linux

image_resource:
  type: registry-image
  source: 
    repository: concourse/oci-build-task
    tag: 0.9

inputs:
  - name: app-source

outputs:
  - name: app-image

params: 
  CONTEXT: app-source/Dockerfile

run:
  path: build
