---
platform: linux

image_resource:
  type: registry-image
  source: 
    repository: denoland/deno
    tag: debian-1.20.6

inputs: 
  - name: deno-app

run:
  path: /usr/bin/deno
  args: ((deno_run_args))
