---
platform: linux

image_resource:
  type: registry-image
  source: 
    repository: denoland/deno
    tag: debian-1.20.6

inputs:
  - name: app

run:
  path: /bin/bash
  args: 
    - -c
    - ((deno_command_and_args))
