---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: fhivemind/concourse-dind

inputs:
  - name: image
  
run:
  path: bash
  args: 
    - -c
    - |
      mkdir -p $HOME/.ssh
      echo "((thinkcenter_ssh_config))" > $HOME/.ssh/config
      echo "((thinkcenter_ssh_private))" > $HOME/.ssh/thinkcenter_rsa
      echo "((thinkcenter_ssh_public))" > $HOME/.ssh/thinkcenter_rsa.pub
      echo "Setting permissions for SSH keys and directories"
      chmod -R 700 $HOME/.ssh
      chmod 600 $HOME/.ssh/thinkcenter_rsa
      chmod 644 $HOME/.ssh/thinkcenter_rsa.pub
      echo "Adding our SSH key to the agent to communicate with thinkcenter"
      eval $(ssh-agent -s)
      ssh-add $HOME/.ssh/thinkcenter_rsa
      ssh-keyscan thinkcenter.dev > $HOME/.ssh/known_hosts      
      echo "Creating docker context to control the daemon on thinkcenter.dev"
      docker context create remote-thinkcenter --docker "host=ssh://admin@thinkcenter.dev,key=$HOME/.ssh/thinkcenter_rsa"
      docker context use remote-thinkcenter      
      export RUNNING_APP_IMAGE=$(docker ps --format "{{.Image}}" --filter "name=((container_name))" --filter "status=running")      
      if [[ -n "${RUNNING_APP_IMAGE}" ]];
      then
        echo "Stopping and removing containers using ${RUNNING_APP_IMAGE} and deleting the image from the local cache"
        docker stop ((container_name))
        docker rm ((container_name))
        docker rmi ${RUNNING_APP_IMAGE}
      fi

      
      


  