---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: fhivemind/concourse-dind/

inputs:
  - name: image
  
run:
  path: sh
  args: 
    - -c
    - | 
      echo "Listing docker context"
      docker context create remote-thinkcenter --docker "host:tcp://thinkcenter.dev:2375"
      docker context use remote-thinkcenter
      echo "Listing currently running containers"
      docker ps -a
      


  