---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: fhivemind/concourse-dind/

inputs:
  - name: image
  
run:
  path: sh
  args: 
    - -c
    - |
      mkdir -p $HOME/.ssh
      echo "((thinkcenter-ssh-key))" > $HOME/.ssh/thinkcenter_rsa
      ssh-add thinkcenter_rsa
      ssh-keyscan -t rsa thinkcenter.dev >> $HOME/.ssh/.known_hosts
      echo "Listing docker context"
      docker context create remote-thinkcenter --docker "host=ssh://admin@thinkcenter.dev,key=$HOME/.ssh/thinkcenter_rsa"
      docker context use remote-thinkcenter
      echo "Listing currently running containers"
      docker ps -a
      


  