---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker/docker

inputs:
  - name: image
  
run:
  path: sh
  args: 
    - -c
    - | 
      echo "Listing docker context"
      docker context ls
      echo "Listing currently running containers"
      docker ps -a
      echo "About to replace ((old_version)) with ((new_version))"


  