services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik@sha256:8cb20d16e01a53d8d7f7696ac2f1af7d200d5c9984d226ce2299731d9eab6d6c
    restart: unless-stopped
    command:
      - --accesslog.fields.names.StartUTC=drop
    environment:
      - TZ=America/Toronto
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy-dashboard.rule=Host(`traefik.thinkcenter.dev`) && (PathPrefix(`/api/`) || PathPrefix(`/dashboard/`))"
      - "traefik.http.routers.proxy-dashboard.service=api@internal"
      - "traefik.http.routers.proxy-dashboard.tls=true"
      - "traefik.http.middlewares.proxy-dashboard.ipallowlist.sourcerange=127.0.0.1/32, 192.168.1.0/24"
      - "traefik.http.middlewares.auth.basicauth.usersFile=/etc/traefik/auth/htpasswd"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./config/:/etc/traefik/
      - /etc/traefik/auth/:/etc/traefik/auth/
      - /etc/traefik/certs/thinkcenter.dev/:/certs/
      - ./logs/:/var/logs/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

networks:
  default:
    external: true
    name: thinknetwork
