version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    command:
      - --accesslog.fields.names.StartUTC=drop
    environment:
      - TZ=America/Toronto
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./config/:/etc/traefik/
      - ./certs/:/certs/
      - ./logs/:/var/logs/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.thinkcenter.dev`)"
    networks:
      - default
  niceplace1:
    image: niceplace/node-web-app1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.niceplace1.rule=Host(`app1.thinkcenter.dev`)"
      - "traefik.http.routers.niceplace1.entrypoints=websecure"
      - "traefik.http.routers.niceplace1.tls=true"
    networks:
      - default

networks:
  default:
    external: true
    name: thinknetwork
