version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6.1
    restart: unless-stopped
    command:
      - --accesslog.fields.names.StartUTC=drop
    environment:
      - TZ=America/Toronto
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy-dashboard.rule=Host(`traefik.thinkcenter.dev`) && (PathPrefix(`/api/`) || PathPrefix(`/dashboard/`))"
      - "traefik.http.routers.proxy-dashboard.service=api@internal"
      - "traefik.http.routers.proxy-dashboard.tls=true"
      - "traefik.http.middlewares.proxy-dashboard.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.1.0/24"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./config/:/etc/traefik/
      - ./certs/:/certs/
      - ./logs/:/var/logs/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

networks:
  default:
    external: true
    name: thinknetwork
