services:
  actual-server:
    image: actualbudget/actual-server@sha256:ea21a0b6243797d35ef6c4a8713c87efaba8fec3b3663220fa3af61f352fba5e
    container_name: actual
    restart: unless-stopped
    ports:
      - "5006:5006"
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Toronto
    networks:
      - thinknetwork
    labels:
      - traefik.enable=true
      - traefik.http.routers.actual.rule=Host(`actual.thinkcenter.dev`)
      - traefik.http.routers.actual.entrypoints=websecure
      - traefik.http.services.actual.loadbalancer.server.port=5006
