services:
  actual-server:
    image: actualbudget/actual-server@sha256:b733ae30c70a66dc4d03577526e53575a0c04eab4f3ab6ace30934776251058c
    container_name: actual
    restart: unless-stopped
    ports:
      - "5006:5006"
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Toronto
    networks:
      - thinknetwork
    labels:
      - traefik.enable=true
      - traefik.http.routers.actual.rule=Host(`actual.thinkcenter.dev`)
      - traefik.http.routers.actual.entrypoints=websecure
      - traefik.http.services.actual.loadbalancer.server.port=5006
