services:
  actual-server:
    image: actualbudget/actual-server@sha256:b0e732e2c41b3dc468a71548e88ef76d3f0c157fc43d15fa05d14ec1c5747e1e
    container_name: actual
    restart: unless-stopped
    ports:
      - "5006:5006"
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Toronto
    networks:
      - thinknetwork
    labels:
      - traefik.enable=true
      - traefik.http.routers.actual.rule=Host(`actual.thinkcenter.dev`)
      - traefik.http.routers.actual.entrypoints=websecure
      - traefik.http.services.actual.loadbalancer.server.port=5006
