services:
  app:
    image: fireflyiii/core@sha256:063d705b2059c5638f377ae32e64c4e8a4071f147280d4f47e2fa6077b369474
    container_name: firefly-iii
    restart: unless-stopped
    volumes:
      - type: volume
        source: firefly_iii_upload
        target: /var/www/html/storage/upload
      - type: bind
        source: ./database/database.sqlite
        target: /var/www/html/storage/database
    env_file:
      - path: .app.env
        required: true
      - path: .app.secrets.env # Will be created, managed and injected at deploy time by Komodo
        required: true
    networks:
      - thinknetwork
    labels:
      - traefik.enable=true
      - traefik.docker.network=thinknetwork
      - traefik.http.routers.firefly.tls=true
      - traefik.http.routers.firefly.rule=Host(`firefly.thinkcenter.dev`)
      - traefik.http.routers.firefly.entrypoints=websecure
      - traefik.http.services.firefly.loadbalancer.server.port=8080
volumes:
  firefly_iii_upload:
networks:
  thinknetwork:
    external: true
