services:
  app:
    image: fireflyiii/core@sha256:fe4ecec4c2ba2b2978a32b3defaf270407f9fddf0e789a18648121ab84bb68d2
    container_name: firefly-iii
    restart: unless-stopped
    volumes:
      - type: volume
        source: firefly_iii_upload
        target: /var/www/html/storage/upload
      - type: bind
        source: ./database/database.sqlite
        # Note: this folder will be owner by root initially, so we will need to sudo chgrp 33 database/ && sudo chmod g+w database/ ON THE HOST
        # Otherwise write permissions are missing from the DB inside the container because it runs with the www-data user, not root
        target: /var/www/html/storage/database/database.sqlite 
    env_file:
      - path: .app.env
        required: true
      - path: .app.secrets.env # Will be created, managed and injected at deploy time by Komodo
        required: true
    networks:
      - thinknetwork
    labels:
      - traefik.enable=true
      - traefik.docker.network=thinknetwork
      - traefik.http.routers.firefly.tls=true
      - traefik.http.routers.firefly.rule=Host(`firefly.thinkcenter.dev`)
      - traefik.http.routers.firefly.entrypoints=websecure
      - traefik.http.services.firefly.loadbalancer.server.port=8080
volumes:
  firefly_iii_upload:
networks:
  thinknetwork:
    external: true
