services:
  app:
    build: .
    image: firefly-iii-otel
    container_name: firefly-iii
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - type: volume
        source: firefly_iii_upload
        target: /var/www/html/storage/upload
    env_file:
      - path: .app.env
        required: true
      - path: .app.secrets.env # Will be created, managed and injected at deploy time by Komodo
        required: true
    networks:
      - thinknetwork
    labels:
      - traefik.enable=true
      - traefik.docker.network=thinknetwork
      - traefik.http.routers.firefly.tls=true
      - traefik.http.routers.firefly.rule=Host(`firefly.thinkcenter.dev`)
      - traefik.http.routers.firefly.entrypoints=websecure
      - traefik.http.services.firefly.loadbalancer.server.port=8080
      - alloy.service.name=firefly-iii-app
  db:
    image: postgres@sha256:692e5dca0962d91131c4ad681f50fb2b79dffb3ef8d766aef2c8cf671fea4034
    container_name: firefly-iii-db
    restart: unless-stopped
    volumes:
      - type: volume
        source: firefly_iii_db_data
        target: /var/lib/postgresql
    env_file:
      - path: .db.env
        required: true
      - path: .app.secrets.env
        required: true
    networks:
      - thinknetwork
    labels:
      - alloy.service.name=firefly-iii-db

volumes:
  firefly_iii_upload:
  firefly_iii_db_data:

networks:
  thinknetwork:
    external: true
